/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author jwolf
 */
public class ModeratorEditAdvertisement extends javax.swing.JFrame {

    /**
     * Creates new form ModeratorEditAdvertisement
     */
    public ModeratorEditAdvertisement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModeratorEdit_Title_Label = new javax.swing.JLabel();
        ModeratorEdit_Title_Field = new javax.swing.JTextField();
        ModeratorEdit_Details_Label = new javax.swing.JLabel();
        ModeratorEdit_Details_Container = new javax.swing.JScrollPane();
        ModeratorEdit_Details_Field = new javax.swing.JTextArea();
        ModeratorEdit_Category_Label = new javax.swing.JLabel();
        ModeratorEdit_Category_ComboBox = new javax.swing.JComboBox<>();
        ModeratorEdit_Price_Label = new javax.swing.JLabel();
        ModeratorEdit_Price_Field = new javax.swing.JTextField();
        ModeratorEdit_Status_Label = new javax.swing.JLabel();
        ModeratorEdit_Status_ComboBox = new javax.swing.JComboBox<>();
        ModeratorEdit_Update_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Advertisement");

        ModeratorEdit_Title_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ModeratorEdit_Title_Label.setLabelFor(ModeratorEdit_Title_Field);
        ModeratorEdit_Title_Label.setText("Title:");

        ModeratorEdit_Title_Field.setEditable(false);
        ModeratorEdit_Title_Field.setToolTipText("Enter a descriptive title for the item.");

        ModeratorEdit_Details_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ModeratorEdit_Details_Label.setLabelFor(ModeratorEdit_Details_Field);
        ModeratorEdit_Details_Label.setText("Details:");

        ModeratorEdit_Details_Container.setToolTipText("");

        ModeratorEdit_Details_Field.setEditable(false);
        ModeratorEdit_Details_Field.setColumns(20);
        ModeratorEdit_Details_Field.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        ModeratorEdit_Details_Field.setLineWrap(true);
        ModeratorEdit_Details_Field.setRows(5);
        ModeratorEdit_Details_Field.setTabSize(1);
        ModeratorEdit_Details_Field.setToolTipText("Enter details about the item.");
        ModeratorEdit_Details_Field.setWrapStyleWord(true);
        ModeratorEdit_Details_Container.setViewportView(ModeratorEdit_Details_Field);

        ModeratorEdit_Category_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ModeratorEdit_Category_Label.setLabelFor(ModeratorEdit_Category_ComboBox);
        ModeratorEdit_Category_Label.setText("Category:");
        ModeratorEdit_Category_Label.setToolTipText("");

        ModeratorEdit_Category_ComboBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        ModeratorEdit_Price_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ModeratorEdit_Price_Label.setLabelFor(ModeratorEdit_Price_Field);
        ModeratorEdit_Price_Label.setText("Price:");

        ModeratorEdit_Price_Field.setEditable(false);
        ModeratorEdit_Price_Field.setToolTipText("Enter the item's price.");

        ModeratorEdit_Status_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ModeratorEdit_Status_Label.setLabelFor(ModeratorEdit_Status_ComboBox);
        ModeratorEdit_Status_Label.setText("Status:");

        ModeratorEdit_Status_ComboBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        ModeratorEdit_Update_Button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ModeratorEdit_Update_Button.setText("Update Advertisement");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ModeratorEdit_Update_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ModeratorEdit_Category_Label)
                            .addComponent(ModeratorEdit_Details_Label)
                            .addComponent(ModeratorEdit_Price_Label)
                            .addComponent(ModeratorEdit_Title_Label)
                            .addComponent(ModeratorEdit_Status_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ModeratorEdit_Status_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ModeratorEdit_Price_Field)
                            .addComponent(ModeratorEdit_Title_Field)
                            .addComponent(ModeratorEdit_Details_Container)
                            .addComponent(ModeratorEdit_Category_ComboBox, 0, 170, Short.MAX_VALUE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModeratorEdit_Title_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModeratorEdit_Title_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModeratorEdit_Details_Container, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModeratorEdit_Details_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModeratorEdit_Category_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModeratorEdit_Category_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModeratorEdit_Price_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModeratorEdit_Price_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModeratorEdit_Status_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModeratorEdit_Status_Label))
                .addGap(18, 18, 18)
                .addComponent(ModeratorEdit_Update_Button)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModeratorEditAdvertisement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModeratorEditAdvertisement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModeratorEditAdvertisement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModeratorEditAdvertisement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModeratorEditAdvertisement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ModeratorEdit_Category_ComboBox;
    private javax.swing.JLabel ModeratorEdit_Category_Label;
    private javax.swing.JScrollPane ModeratorEdit_Details_Container;
    private javax.swing.JTextArea ModeratorEdit_Details_Field;
    private javax.swing.JLabel ModeratorEdit_Details_Label;
    private javax.swing.JTextField ModeratorEdit_Price_Field;
    private javax.swing.JLabel ModeratorEdit_Price_Label;
    private javax.swing.JComboBox<String> ModeratorEdit_Status_ComboBox;
    private javax.swing.JLabel ModeratorEdit_Status_Label;
    private javax.swing.JTextField ModeratorEdit_Title_Field;
    private javax.swing.JLabel ModeratorEdit_Title_Label;
    private javax.swing.JButton ModeratorEdit_Update_Button;
    // End of variables declaration//GEN-END:variables
}
