/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author jwolf
 */
public class ModeratorScreen extends javax.swing.JFrame {

    /**
     * Creates new form ModeratorScreen
     */
    public ModeratorScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ad_Title_Field = new javax.swing.JTextField();
        Ad_Title_Label = new javax.swing.JLabel();
        Ad_Details_Field_Container = new javax.swing.JScrollPane();
        Ad_Details_Field = new javax.swing.JTextArea();
        Ad_Details_Label = new javax.swing.JLabel();
        Ad_Category_ComboBox = new javax.swing.JComboBox<>();
        Ad_Category_Label = new javax.swing.JLabel();
        Ad_Price_Field = new javax.swing.JTextField();
        Ad_Price_Label = new javax.swing.JLabel();
        Add_Advertisement_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Advertisement");

        Ad_Title_Field.setToolTipText("Enter a title for the advertisement.");

        Ad_Title_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Ad_Title_Label.setLabelFor(Ad_Title_Field);
        Ad_Title_Label.setText("Title:");

        Ad_Details_Field.setColumns(20);
        Ad_Details_Field.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Ad_Details_Field.setLineWrap(true);
        Ad_Details_Field.setRows(5);
        Ad_Details_Field.setToolTipText("Enter details about the item being advertised.");
        Ad_Details_Field.setWrapStyleWord(true);
        Ad_Details_Field_Container.setViewportView(Ad_Details_Field);

        Ad_Details_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Ad_Details_Label.setLabelFor(Ad_Details_Field);
        Ad_Details_Label.setText("Details:");

        Ad_Category_ComboBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        Ad_Category_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Ad_Category_Label.setLabelFor(Ad_Category_ComboBox);
        Ad_Category_Label.setText("Category:");

        Ad_Price_Field.setToolTipText("Enter the price for the item being advertised.");

        Ad_Price_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Ad_Price_Label.setLabelFor(Ad_Price_Field);
        Ad_Price_Label.setText("Price:");

        Add_Advertisement_Button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Add_Advertisement_Button.setText("Add Advertisement");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Ad_Title_Label)
                    .addComponent(Ad_Details_Label)
                    .addComponent(Ad_Category_Label)
                    .addComponent(Ad_Price_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Add_Advertisement_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ad_Price_Field)
                    .addComponent(Ad_Category_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ad_Details_Field_Container)
                    .addComponent(Ad_Title_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ad_Title_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ad_Title_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ad_Details_Label)
                    .addComponent(Ad_Details_Field_Container, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ad_Category_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ad_Category_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ad_Price_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ad_Price_Label))
                .addGap(18, 18, 18)
                .addComponent(Add_Advertisement_Button)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModeratorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModeratorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModeratorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModeratorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModeratorScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Ad_Category_ComboBox;
    private javax.swing.JLabel Ad_Category_Label;
    private javax.swing.JTextArea Ad_Details_Field;
    private javax.swing.JScrollPane Ad_Details_Field_Container;
    private javax.swing.JLabel Ad_Details_Label;
    private javax.swing.JTextField Ad_Price_Field;
    private javax.swing.JLabel Ad_Price_Label;
    private javax.swing.JTextField Ad_Title_Field;
    private javax.swing.JLabel Ad_Title_Label;
    private javax.swing.JButton Add_Advertisement_Button;
    // End of variables declaration//GEN-END:variables
}
