/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author jwolf
 */
public class UserEditAdvertisement extends javax.swing.JFrame {

    /**
     * Creates new form UserEditAdvertisement
     */
    public UserEditAdvertisement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserEdit_Title_Label = new javax.swing.JLabel();
        UserEdit_Title_Field = new javax.swing.JTextField();
        UserEdit_Details_Label = new javax.swing.JLabel();
        UserEdit_Details_Container = new javax.swing.JScrollPane();
        UserEdit_Details_Field = new javax.swing.JTextArea();
        UserEdit_Category_Label = new javax.swing.JLabel();
        UserEdit_Category_ComboBox = new javax.swing.JComboBox<>();
        UserEdit_Price_Label = new javax.swing.JLabel();
        UserEdit_Price_Field = new javax.swing.JTextField();
        UserEdit_Update_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Advertisement");

        UserEdit_Title_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UserEdit_Title_Label.setText("Title:");

        UserEdit_Title_Field.setToolTipText("Enter a descriptive title for the item.");

        UserEdit_Details_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UserEdit_Details_Label.setText("Details:");

        UserEdit_Details_Container.setToolTipText("");

        UserEdit_Details_Field.setColumns(20);
        UserEdit_Details_Field.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        UserEdit_Details_Field.setLineWrap(true);
        UserEdit_Details_Field.setRows(5);
        UserEdit_Details_Field.setTabSize(1);
        UserEdit_Details_Field.setToolTipText("Enter details about the item.");
        UserEdit_Details_Field.setWrapStyleWord(true);
        UserEdit_Details_Container.setViewportView(UserEdit_Details_Field);

        UserEdit_Category_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UserEdit_Category_Label.setText("Category:");
        UserEdit_Category_Label.setToolTipText("");

        UserEdit_Category_ComboBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        UserEdit_Price_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UserEdit_Price_Label.setText("Price:");

        UserEdit_Price_Field.setToolTipText("Enter the item's price.");

        UserEdit_Update_Button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UserEdit_Update_Button.setText("Update Advertisement");
        UserEdit_Update_Button.setToolTipText("Save changes to the advertisement.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UserEdit_Update_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UserEdit_Category_Label)
                            .addComponent(UserEdit_Details_Label)
                            .addComponent(UserEdit_Price_Label)
                            .addComponent(UserEdit_Title_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UserEdit_Price_Field)
                            .addComponent(UserEdit_Title_Field)
                            .addComponent(UserEdit_Details_Container)
                            .addComponent(UserEdit_Category_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserEdit_Title_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserEdit_Title_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserEdit_Details_Container, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserEdit_Details_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserEdit_Category_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserEdit_Category_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserEdit_Price_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserEdit_Price_Label))
                .addGap(18, 18, 18)
                .addComponent(UserEdit_Update_Button)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserEditAdvertisement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserEditAdvertisement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserEditAdvertisement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserEditAdvertisement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserEditAdvertisement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> UserEdit_Category_ComboBox;
    private javax.swing.JLabel UserEdit_Category_Label;
    private javax.swing.JScrollPane UserEdit_Details_Container;
    private javax.swing.JTextArea UserEdit_Details_Field;
    private javax.swing.JLabel UserEdit_Details_Label;
    private javax.swing.JTextField UserEdit_Price_Field;
    private javax.swing.JLabel UserEdit_Price_Label;
    private javax.swing.JTextField UserEdit_Title_Field;
    private javax.swing.JLabel UserEdit_Title_Label;
    private javax.swing.JButton UserEdit_Update_Button;
    // End of variables declaration//GEN-END:variables
}
